applied patch from 1.00b to 1.50b (so far latest)

diff --git a/afl-plot b/afl-plot
--- a/afl-plot
+++ b/afl-plot
@@ -6,7 +6,7 @@
 # Written and maintained by Michal Zalewski <lcamtuf@google.com>
 # Based on a design & prototype by Michael Rash.
 #
-# Copyright 2014 Google Inc. All rights reserved.
+# Copyright 2014, 2015 Google Inc. All rights reserved.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -34,6 +34,19 @@ you should be able to view it with any web browser of your choice.
 
 _EOF_
 
+  exit 1
+
+fi
+
+echo "$1" | grep -qE '^(/var)?/tmp/'
+T1="$?"
+
+echo "$2" | grep -qE '^(/var)?/tmp/'
+T2="$?"
+
+if [ "$T1" = "0" -o "$T2" = "0" ]; then
+
+  echo "Error: do not use shared /tmp or /var/tmp directories with this script." 1>&2
   exit 1
 
 fi
@@ -140,6 +153,10 @@ cat >"$2/index.html" <<_EOF_
 <img src="exec_speed.png" width=1000 height=200>
 
 _EOF_
+
+# Make it easy to remotely view results when outputting directly to a directory
+# served by Apache or other HTTP daemon. Since the plots aren't horribly
+# sensitive, this seems like a reasonable trade-off.
 
 chmod 755 "$2"
 chmod 644 "$2/high_freq.png" "$2/low_freq.png" "$2/exec_speed.png" "$2/index.html"
